#' @import dplyr
#' @param dep_tbl dependency table as generated by function get_GN_dep_ratio_mult
#' @param pop population tibble created from reading IMF WEO dataset



avg_dep_ratios <- function(dep_tbl, pop) {

  pop2 <- pop %>%
    mutate(country = str_extract(SERIES_CODE, "^.{3}")) %>%
    select(7:34) %>%
    relocate(country) %>%
    pivot_longer(3:last_col(), names_to = "year") %>%
    filter(country %in% dep_tbl$country) %>%
    filter(year %in% years) %>%
    arrange(country, year)


  dep_all2 <- dep_tbl %>%
    filter(country != "ROW") %>%
    arrange(country,year) %>%
    add_column(pop = pop2$value)

  val <- na.omit(dep_all2) %>%
    mutate(dep_x_pop = GN_dep_ratio * pop) %>%
    select(GN_dep_ratio, dep_x_pop, pop, year) %>%
    group_by(year) %>%
    summarize(av = mean(GN_dep_ratio),
              dep_x_pop = sum(dep_x_pop),
              pop = sum(pop)
    ) %>%
    mutate(wt_av = dep_x_pop/pop, .keep = "unused")
  return(val)
}
