#' @import ggplot
#' @import sf
#' @import dplyr
#' @param year_plot year of the plot you want
#' @param dep_all dependency table as generated by function get_GN_dep_ratio_mult
#' @param c_GN country list of GN with dependency set to 1, tibble with 2 cols: country and GN_dep_ratio

world_dep_map <- function(year_plot, dep_all, c_GN){
  theme_set(theme_bw())

  world <- rnaturalearth::ne_countries(scale = "medium", returnclass = "sf")

  dep_map <-  dep_all %>%
    filter(country != "ROW") %>%
    arrange(country,year) %>%
    filter(year == year_plot) %>%
    select(country, GN_dep_ratio) %>%
    na.omit

  dep_map <- rbind(dep_map, c_GN)

  world$dep_ratio <- dep_map$GN_dep_ratio[match(world$iso_a3, dep_map$country)]

  map_title <- if ("sector" %in% colnames(dep_all)) {
    paste0("World map of ", dep_all$sector[1], " dependency on GN in ", year_plot)
  }
  else paste0("World map of dependency on GN in ", year_plot)

  dep_map_gg <-  ggplot(data = world) +
    geom_sf(aes(fill = dep_ratio)) +
    scale_fill_gradientn(colours = terrain.colors(10), limits = c(0,1)) +
    ggtitle(map_title,
            subtitle = paste0("(", length(dep_map$country), " countries)")
    )
  return(dep_map_gg)
}
